lacework/terraform-provisioning

aws/main.tf
azure/main.tf
gcp/main.tf

We have a bug on the platform that if two token requests come at the
same time (~2ms difference) the platform will generate two tokens and
lockdown the API access key, to avoid that we are adding a dependency to
every lacework resource to call it one by one until we fix the bug in
the platform.

fix: add dependencies to avoid tocken lockdown

---

aws/main.tf
aws/variables.tf

Fixing a quick bug where we are using the `ARN` instead of the `URL` of the
SQS queue. Additionally, we are adding a `cross_account_policy_name` variable.

fix(aws): use SQS URL instead of ARN

---

gcp/README.md

This adds a step-by-step `README` to walk users through automating and integrating GCP environments with Lacework

docs(GCP README) Add step-by-step README.md for GCP

---

gcp/README.md

Add environment variables to GCP README. Addressing #24 for GCP.

Add env vars to GCP README

---

.gitignore
gcp/main.tf
gcp/variables.tf

PR to enable required APIs for GCP integration via Terraform. Also gitignore updates to ignore all json files from being accidentally committed. Addressing issue #26

[GCP] Include required GCP APIs and gitignore update

---

gcp/README.md
gcp/variables.tf

Terraform documentation says that the prefix is `TF_VAR` instead of `TF_VARS`,
this change updates the `README.md` to use such prefixes:
https://www.terraform.io/docs/commands/environment-variables.html#tf_var_name
Additionally, added a nitpick change to remove empty lines from `gcp/variables.tf`

docs(gcp): fix TF_VAR prefix in README.md

---

aws/modules/cloudtrail/examples/existing-cloudtrail-iam-role/main.tf
aws/modules/cloudtrail/examples/existing-cloudtrail/main.tf
aws/modules/cloudtrail/main.tf
aws/modules/cloudtrail/variables.tf

This update renames the `enable_cloudtrail` attribute to `use_existing_cloudtrail`
The default behavior now is setup `use_existing_cloudtrail = false` which enables cloudtrail on the account Terraform is be executed against. If a user wants to use an existing cloudtrail they will set the attribute to `use_existing_cloudtrail = true`. Examples have been updated to reflect this change...
```
provider "lacework" { }
provider "aws" { }
module "aws_cloudtrail" {
source = "../../"
use_existing_cloudtrail    = true
bucket_name                = "lacework-ct-bucket-7bb591f4"
sns_topic_name             = "lacework-ct-sns-7bb591f4"
use_existing_iam_role = true
iam_role_name         = "lacework_iam_role"
iam_role_external_id  = "1GrDkEZV5VJ@=nLm"
}
```
This new behavior is consistent with the …

chore(aws) rename enable_cloudtrail => use_existing_cloudtrail

---

aws/README.md
aws/modules/cloudtrail/variables.tf
aws/modules/config/variables.tf

Re-write of the AWS README to document usage of the new TF modules. 

docs(README) Update AWS README for module refactor

---

gcp/main.tf

This is a bug-fix that will allow users create Organization and Project
level integrations. Before we were creating only Project level
integrations.

fix(gcp): pass resource_level to LW integrations

---

gcp/README.md
gcp/main.tf

Closes https://github.com/lacework/terraform-provisioning/issues/42
Closes https://github.com/lacework/terraform-provisioning/issues/43

fix(gcp): use correct resource_id for ORG or PROJ

---

aws/README.md
aws/modules/cloudtrail/examples/complete-cloudtrail/main.tf
aws/modules/cloudtrail/examples/consolidated-cloudtrail-multiple-lacework-tenants/main.tf
aws/modules/cloudtrail/examples/consolidated-cloudtrail-multiple-lacework-tenants/sub_account.tf
aws/modules/cloudtrail/examples/consolidated-cloudtrail/main.tf
aws/modules/cloudtrail/examples/existing-cloudtrail-iam-role/main.tf
aws/modules/cloudtrail/examples/existing-cloudtrail/main.tf
aws/modules/cloudtrail/main.tf
aws/modules/cloudtrail/output.tf
aws/modules/cloudtrail/variables.tf
aws/modules/config/output.tf

Closes https://github.com/lacework/terraform-provisioning/issues/32
This example enables a new Consolidated CloudTrail and IAM Role for Lacework,
then configures both integrations with Lacework, finally, it configures a new
CloudTrail in an AWS sub-account that points to the main CloudTrail.
```hcl
provider "lacework" {
alias = "main"
}
provider "aws" {
alias = "main"
}
module "main_cloudtrail" {
source    = "github.com/lacework/terraform-provisioning/aws/modules/cloudtrail"
providers = {
aws      = aws.main
lacework = lacework.main
}
consolidated_trail = true
}
provider "aws" {
alias = "sub_account"
}
resource "aws_cloudtrail" "lw_sub_account_cloudtrail" {
provider              = aws.sub_account
name                  = "lacework-sub-trail"
is_multi_region_trail = true
s3_bucket_name …
```

feat(aws): consolidated cloudtrail + multitenancy

---

aws/README.md
aws/modules/cloudtrail/output.tf

This will avoid users to use a `aws_sqs_queue` data source to get the SQS ARN if they need it.

chore(aws): expose cloudtrail SQS ARN

---

gcp/modules/audit_log/variables.tf
gcp/modules/service_account/variables.tf

When doing some deep testing of the GCP modules, one use-case we have seen
with our customers is the **creation of a new GCP project that needs to be linked
to their Lacework account to be monitored right after its creation.** For example:
```hcl
provider "google" {}
provider "lacework" {}
resource "google_project" "new" {
name       = "new-project"
project_id = "project-123"
org_id     = "1234567890"
}
module "new_project_gcp_config" {
source     = "git::https://github.com/lacework/terraform-provisioning.git//gcp/modules/config"
project_id = google_project.new.id
}
```
The above example will create a new Google Cloud project and configure it to
be monitored by Lacework.
This scenario requires the `service_account` module to have the following APIs enabled:
* serviceusage.googleapis.com
* …

fix(gcp): activate required apis correctly

---

README.md

Using admin privileges since it is a one-line update to our README.md

chore: update Lacework's support website

---

aws/README.md
aws/main.tf

original main.tf example produced following error when terraform init was executed:
`$ terraform init
Initializing modules...
Downloading https://github.com/lacework/terraform-provisioning/aws/modules/cloudtrail for aws_cloudtrail...
Downloading https://github.com/lacework/terraform-provisioning/aws/modules/config for aws_config...
Error: Failed to download module`
Removed leading "https://"
Also minor edits to readme to improve readability.

docs(aws): Fixed typos and corrected main.tf example

---

aws/README.md
aws/modules/cloudtrail/main.tf
aws/modules/cloudtrail/variables.tf
aws/modules/config/main.tf
aws/modules/config/variables.tf
aws/modules/iam_role/main.tf
aws/modules/iam_role/variables.tf
gcp/README.md
gcp/modules/audit_log/main.tf
gcp/modules/audit_log/variables.tf

Parameterize the create_duration parameter for time_sleep resources. 
Closes https://github.com/lacework/terraform-provisioning/issues/61

feat(aws): parameterize time_sleep duration with input wait_time

---

azure/modules/ad_application/main.tf

The documentation for the `application_password` resource says:
>`application_object_id` - (Required) The Object ID of the Application
>for which this password should be created. Changing this field forces
>a new resource to be created.
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_password#application_object_id
We were using the wrong id. :facepalm:

fix(azure): use object id instead of principal id

---

azure/README.md
azure/modules/activity_log/main.tf
azure/modules/activity_log/variables.tf
azure/modules/ad_application/examples/all-subscriptions-ad-application/main.tf
azure/modules/ad_application/examples/custom-ad-application/main.tf
azure/modules/ad_application/main.tf
azure/modules/ad_application/variables.tf
azure/modules/config/examples/custom-config/main.tf
azure/modules/config/examples/default-config/main.tf
azure/modules/config/main.tf
azure/modules/config/variables.tf

We have introduced the following behavior when choosing which
subscriptions to grant read access to:
* By default, we grant access to only the primary subscription
* If the user prefers to, they can provide a list of subscriptions to grant read access to
* Finally, users can also opt to grant read access to ALL subscriptions within a tenant
New inputs:
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| subscription_ids | A list of subscriptions to grant read access to, by default the modules will only use the primary subscription | `list(string)` | `[]` | no |
| all_subscriptions | If set to true, grant read access to ALL subscriptions within the selected Tenant (overrides `subscription_ids`) | `bool` | false | no |
Signed-off-by: Salim …

feat(azure): configure flexible subscription ids

---

azure/README.md

Updating example in main Azure README to pin azurerm provider at 2.26 to address bug in the provider. 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8426

docs(azure): pin azurerm provider to 2.26

---

azure/AZURE_CLOUD_SHELL.md
azure/shell_startup.sh

This change updates the Azure shell docs and the script to provide a clearer message to `exit` the current shell rather than restarting the the shell, as a restart removes the installation of the CLI and TF v.0.12.x

docs(azure) Update docs for exiting Azure shell instead of restart

---

azure/shell_startup.sh
gcp/GOOGLE_CLOUD_SHELL.md
gcp/shell_startup.sh

This PR updates GCP Cloud Shell docs to explicitly state to `exit` shell rather than "restart" the shell, which mirrors our Azure Shell docs.

docs(gcp) Update GCP Cloud Shell docs to exit shell

---

Dockerfile

This image is being used by all our Terraform Modules and Provider!
Example: https://github.com/lacework/terraform-aws-config/pull/3

ci: add Terraform 13 image

---

azure/shell_startup.sh

This PR is updating the `shell_startup.sh` script to use the default version of Terraform that comes from the Cloud Shell which is 13.X, additionally, we are adding extra checks to verify the required privileges of the user running this automation.
When a user doesn't have the Global Admin role, they will see the following output:
If the user has all the required permissions, they will see the following output:

fix(azure): update shell_startup.sh to use Terraform 13

---

aws/modules/cloudtrail/main.tf

- Added logic to gracefully handle a trailing slash in the `bucket_arn` variable. Fixes #102

fix(aws): gracefully handle trailing slash in bucket_arn

---

azure/modules/activity_log/main.tf
azure/modules/activity_log/variables.tf
azure/modules/ad_application/variables.tf
azure/modules/config/variables.tf

- Added unique suffix to Azure resources
- Updated 'azurerm_role_definition.lacework.id' to 'azurerm_role_definition.lacework.role_definition_resource_id'  (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#example-usage-custom-role--service-principal)
- Changed default prefix from 'l4c3w0rk' to 'lacework'

fix(azure): added unique suffix to Azure resources

---

README.md

This PR updates the README to warn about the deprecation for the project. New documentation shows were to find the new modules on Terraform Registry and on GitHub. New documentation also points to new support.lacework.com docs.

docs(readme) Deprecating project

---

gcp/shell_startup.sh

Azure Cloud Shells are always up-to-date to provision VMs with the latest
version of Terraform, but Google Cloud Shell are not, so we are installing
the latest version for our users.
Current Version on Google Cloud Shell VMs:

feat(gcp): upgrade terraform inside shell_startup.sh

---

azure/shell_startup.sh

Well, Microsoft changed the Role name from `Company Administrator` to `Global Administrator`... Why Microsoft?
https://docs.microsoft.com/en-us/answers/questions/233909/get-azureaddirectoryrole-and-34global-administrato.html
To test this modification run the following command on your Azure Cloud Shell:
```
curl https://raw.githubusercontent.com/lacework/terraform-provisioning/b4b87ebaf347f19f01ea7dff96d366cda72337ee/azure/shell_startup.sh | bash
```

fix(azure): Microsoft role rename in shell_startup.sh

---

Dockerfile

From the Codecov breach, Hashicorp had to rotate their GPG key and with
that, they had to release a new version of their Terraform CLI:
https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570
We are upgrading the version of our containers to the recommended
version.

fix: upgrade our Terraform docker containers

---

azure/shell_startup.sh

When a customer uses the shell_startup.sh script and
he/she has multiple roles assigned, the script doesn’t
handle this case well and says that the user doesn’t have
the Owner Role, even when he/she does have it.
JIRA: https://lacework.atlassian.net/browse/ALLY-563

fix: azure shell startup script for multiple roles

---

azure/shell_startup.sh

Previous version was looking only for explicit Owner Role at the Subscription level, not taking into account inheritance from Management Groups.

feat: Check for Owner Role assignment by Inheritance

---

azure/shell_startup.sh

We were trying to run this Script as the administrator/owner of the Azure tenant/subscription and we encountered errors. We had to switch the reference to be `.id` instead of `.objectId` as the `objectId` key did not exist and the value `null` was getting assigned when performing the Owner permissions User check. When we changed it to `.id`, the script began to function as we expected.

fix: attribute reference causing owner to not be identified

---

azure/shell_startup.sh

Currently the script only gets roles that are assigned to the user directly.
Added the `--include-groups` flag so that it gets roles assigned via groups as well.
Also removed the jq select because the principalId will be that of the group, not the user.

fix: include azure roles assigned via groups
